Fix  strange BootstrapMethodError when running `gradle test` under Java 8  (on Mac OS X).
opprop/generic-type-inference-solver pull request #19
Opened 2017-06-08 16:44 UTC by CharlesZ-Chen

When running `gradle test` under Java 8 on my machine (Mac OS X), I will get below error:

```
java.lang.BootstrapMethodError: call site initialization exception
        at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
        at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
        at java.io.ObjectInputStream.<clinit>(ObjectInputStream.java:3578)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:80)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:45)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
Caused by: java.lang.ClassCastException: bootstrap method failed to produce a CallSite
        at java.lang.invoke.CallSite.makeSite(CallSite.java:332)
        ... 7 more
:test FAILED
``` 

The only possible reason for this is I add checker-framework version of `javac` (we need to use cf-version of javac under java 7 to running test, to avoid the `NoSuchFieldError` according to the cf manual.) into the `bootstrapclasspath` when running tests.

I have no idea of why this strange error happens, so as a workaround, I add a check statement in gradle test, to only add the cf-version of `javac` when running test under Java 7.

2017-06-08 18:38 UTC, topnessman reviewed
I don't know the reason. But I found your comment doesn't match the implementation -  "Need to use Checker Framework version of javac when running under Java 7". But why are you using inference javac.jar? Can it be the reason?

2017-06-08 18:42 UTC, CharlesZ-Chen commented
The `javac.jar` in inference is copied from checker-framework. Let me try to use the one in cf.

2017-06-08 21:57 UTC, wmdietl commented
If nobody is using the copy of `javac.jar` we should also remove the logic that copied that file around.
I would guess that annotations-in-comments will stop working with this change, as you're no longer using the jsr308-langtools javac.

Is the fix from https://groups.google.com/forum/#!searchin/checker-framework-dev/BootstrapMethodError%7Csort:relevance/checker-framework-dev/eNJU6qiqhGQ/5E2jc1NiCAAJ
not working for you?
Did you rebuild the javac on your MacOS system or are you reusing the binary javac.jar from somewhere else?

2017-06-09 18:22 UTC, CharlesZ-Chen commented
Hi Prof. Dietl, Thanks for the comment! It turns out the reason is I didn't rebuild the javac.jar on my Mac OS X system.

After I manually go into `jsr308-langtool/make`, run `ant clean build-javac build-javap`, and then re-build the checker-framework, the strange error has gone.

The strange thing is that I need to go into `jsr308-langtool/make` dir to manually rebuild `javac.jar`, i.e. directly re-build the checker-framework by doing `ant` won't rebuild the `javac.jar`. Is it an expected behaviour (when re-building checker-framework, it doesn't re-build the javac.jar)?

2017-06-11 05:13 UTC, wmdietl commented
Hi Charles,
Yes, the projects normally don't rebuild each other. It is not enough to rebuild the Checker Framework if dependencies like AFU or javac changed.
(The only exception to that is the initial build through the Travis scripts, which clones or updates all dependencies.)

Is it worth adding a note about 1. the problem you ran into and 2. this project rebuild behavior somewhere in the Checker Framework manual?

2017-06-11 05:13 UTC, wmdietl requested changes
From the discussion it sounds like we won't merge this PR.

2017-06-12 16:05 UTC, CharlesZ-Chen commented
Close this PR as above discussed.

2017-06-12 16:05 UTC, closed without merging

2017-06-12 16:14 UTC, CharlesZ-Chen commented
Hi Prof. Dietl @wmdietl :

Yes, I think it would be valuable if we note this problem, as the solution need cf-specific-experiences and hard to troubleshooting by googling. When I troubleshooting this problem, it's kind a hard for me to search anything related to this specific strange exception. But it turns out the reason is just I didn't rebuild jsr308-javac in my machine...

Would https://checkerframework.org/manual/#troubleshooting `32.1.5 Unable to build the checker, or to run programs`  a proper place to record this problem?